version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: juancodev
      POSTGRES_PASSWORD: jmontilla123
      POSTGRES_DB: nestdb
    ports:
      - 5499:5432